<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
            http://maven.apache.org/POM/4.0.0
            https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>br.com.defaultcompany</groupId>
    <artifactId>default-company-crm</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>

        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <javafx.version>21.0.7</javafx.version>
        <jooq.version>3.20.7</jooq.version>
        <mysql.version>9.4.0</mysql.version>

    </properties>

    <dependencies>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
            <classifier>linux</classifier>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
            <classifier>linux</classifier>
        </dependency>

        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mindrot</groupId>
            <artifactId>jbcrypt</artifactId>
            <version>0.4</version>
        </dependency>

        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>${jooq.version}</version>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>

                <configuration>
                    <release>21</release>
                </configuration>

            </plugin>

            <plugin>

                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>

                <configuration>
                    <mainClass>
                        br.com.defaultcompany.Main
                    </mainClass>
                </configuration>

            </plugin>

            <plugin>

                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>

                <dependencies>

                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-codegen</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>com.mysql</groupId>
                        <artifactId>mysql-connector-j</artifactId>
                        <version>${mysql.version}</version>
                    </dependency>

                </dependencies>

                <executions>

                    <execution>

                        <id>generate-jooq</id>

                        <phase>generate-sources</phase>

                        <goals>
                            <goal>generate</goal>
                        </goals>

                        <configuration>

                            <jdbc>

                                <driver>com.mysql.cj.jdbc.Driver</driver>

                                <url>
                                    jdbc:mysql://localhost:3306/projetos
                                </url>

                                <user>root</user>

                                <password>senha.admin</password>

                            </jdbc>

                            <generator>

                                <database>

                                    <name>
                                        org.jooq.meta.mysql.MySQLDatabase
                                    </name>

                                    <inputSchema>
                                        projetos
                                    </inputSchema>

                                </database>

                                <target>

                                    <packageName>
                                        br.com.defaultcompany.jooq
                                    </packageName>

                                    <directory>
                                        target/generated-sources/jooq
                                    </directory>

                                </target>

                            </generator>

                        </configuration>

                    </execution>

                </executions>

            </plugin>

        </plugins>

    </build>

</project>